apiVersion: v1
kind: Secret
metadata:
  name: helep-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    # keep the secret even if helm is rolled back
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.global.jwtSecret | quote }}
