apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "svc.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep   # survive helm rollback
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: {{ .Values.pvcSize }}
